### ISSUE TITLE
sample build failed

### ISSUE THREAD

**Issue by mplazac** [regulaforensics/cordova-plugin-documentreader-mrz#1]
Hello, building your sample I get the following error:

`
Task :app:compileDebugJavaWithJavac FAILED
24 actionable tasks: 1 executed, 23 up-to-date
 Error output:
X:\test\testdocumentreader\platforms\android\app\src\main\java\cordova.plugin.documentreader\DocumentReader.java:123: error: cannot find symbol
                                Bitmap bitmap = documentReaderResults.getGraphicFieldImageByType(eGraphicFieldType.GT_DOCUMENT_FRONT);
                                                                                                                  ^
  symbol:   variable GT_DOCUMENT_FRONT
  location: class eGraphicFieldType
`

Requirements check results for android:

- Java JDK: installed 1.8.0 ( Java SE Development Kit 8 Update 221  64-bit )
- Android SDK: installed true
- Android target: installed android-29,android-28,android-27
- Gradle: installed C:\Gradle\gradle-5.6.2\bin\gradle

Thanks in advance.

**Comment by vyakimchik** [comment]
Hello,

I guess that you are using the SDK 5.0 (Beta), where `GT_DOCUMENT_REAR` was removed and `GT_DOCUMENT_FRONT` was renamed to `GF_DOCUMENT_IMAGE` (see `eGraphicFieldType` enum). In order to get the appropriate document side you should use the new property `pageIndex`, which is available in `DocumentReaderGraphicResult` class, e.g. `pageIndex` = 0 - it’s the first (front) side of the document, `pageIndex` = 1 - it’s the second (back) side of the document.

The documentation and the release version of SDK for Cordova will be available soon. Meanwhile, you can see the changelog [here](https://docs.regulaforensics.com/android/changelog) and migration guide [here](https://docs.regulaforensics.com/android/migration-guide) for native Android SDK.

Link to the whole documentation: [https://docs.regulaforensics.com/home/](https://docs.regulaforensics.com/home/).

**Comment by mplazac** [comment]
Hi, thanks for your speed reply. Maybe I missed out to point out that I get the compilation error building the project using  the cordova-plugin-documentreader-mrz.

**Comment by vyakimchik** [comment]
Try to use 4.2.1 version of the SDK. It'll solve these errors. If any questions appear, feel free to contact us.

**Comment by mplazac** [comment]
Can you please indicate the procedure to change or target the default SDK ? ( Just following the indications, Cordova downloads & generates all the files )
